version: '3.3'
services:
  database:
    container_name: database
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: username
      MYSQL_DATABASE: dbname
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    links:
      - "database"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
       - "8080:80"
    depends_on:
      - database
      
  bookstack:
    build: .
    container_name: bookstack-container
    links:
      - "database"
    ports:
      - "80:80"
    depends_on:
      - database
    command: "/usr/sbin/apache2ctl -D FOREGROUND"
